server:
  port: 9094


spring:
  datasource:
    url: jdbc:mysql://rm-xxxx.mysql.rds.aliyuncs.com:3306/databasename
    username: username
    password: password
    driver-class-name: com.mysql.jdbc.Driver